Giving up, using pre-made action stefanzweifel/git-auto-commit-action

diff --git a/.github/workflows/build-command.yml b/.github/workflows/build-command.yml
--- a/.github/workflows/build-command.yml
+++ b/.github/workflows/build-command.yml
@@ -74,21 +74,25 @@ jobs:
             > Running script `./build.sh`
       - name: Run build script
         run: ./build.sh
-      - run: git status
-      - name: Check if changes were made
-        id: check-changes
-        run: git diff --exit-code
-        # https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code
-        # Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.
-        # 0 is success (no difference), non-zero (like 1) is failure (differences)
-        continue-on-error: true
-      - name: Commit changes to the PR branch
-        if: ${{ failure() && steps.check-changes.outputs == 'failure' }}
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
-          git diff --quiet && git diff --staged --quiet || (git commit -am "[build-command] Update generated files")
-          git push
+      - uses: stefanzweifel/git-auto-commit-action@v4
+        id: auto-commit-action
+        with:
+          commit_message: "[build-command] Update generated files"
+      # - run: git status
+      # - name: Check if changes were made
+      #   id: check-changes
+      #   run: git diff --exit-code
+      #   # https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code
+      #   # Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.
+      #   # 0 is success (no difference), non-zero (like 1) is failure (differences)
+      #   continue-on-error: true
+      # - name: Commit changes to the PR branch
+      #   if: ${{ failure() && steps.check-changes.outputs == 'failure' }}
+      #   run: |
+      #     git config --global user.name 'github-actions[bot]'
+      #     git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
+      #     git diff --quiet && git diff --staged --quiet || (git commit -am "[build-command] Update generated files")
+      #     git push
       - name: Add reaction
         uses: peter-evans/create-or-update-comment@v2
         with:
@@ -99,7 +103,7 @@ jobs:
           issue-number: ${{ github.event.inputs.issue-number }}
           reaction-type: hooray
       - name: Create final comment updated files
-        if: steps.check-changes.outputs.outcome == 'failure'
+        if: steps.auto-commit-action.outputs.changes_detected == 'true'
         uses: peter-evans/create-or-update-comment@v2
         with:
           ## Use token if we want to use a PAT instead of GITHUB_TOKEN, GITHUB_TOKEN acts as github-actions[bot]
@@ -110,7 +114,7 @@ jobs:
           body: |
             > Build command workflow completed updating files.
       - name: Create final comment no updated files
-        if: steps.check-changes.outputs.outcome == 'success'
+        if: steps.auto-commit-action.outputs.changes_detected == 'false'
         uses: peter-evans/create-or-update-comment@v2
         with:
           ## Use token if we want to use a PAT instead of GITHUB_TOKEN, GITHUB_TOKEN acts as github-actions[bot]
